### ISSUE TITLE
Hantek365E

### ISSUE THREAD

**Issue by kangpyo** [mp035/hantek-365#27]
Hi, can I use this software for Hantek365E? 
It recognizes the device when I test it with the .hantek command in cli folder. 
But it doesn't give any response to the GUI.

**Comment by mp035** [comment]
I am not sure, I don't have a 365e.  Do you get any readings from the command line application?

**Comment by kangpyo** [comment]
Yes, it read the data from the command line but it just won't appear in the GUI.

**Comment by mp035** [comment]
Can you please post the terminal output you get when you start the GUI from the command line?

**Comment by kangpyo** [comment]
![Screenshot from 2022-12-05 19-27-32](https://user-images.githubusercontent.com/53060924/205776054-427cf4aa-c084-4c41-931c-e18d21ec422a.png)
![Screenshot from 2022-12-05 19-27-18](https://user-images.githubusercontent.com/53060924/205776073-7005b1b2-b656-4af9-8241-3f5900299e7c.png)

**Comment by kangpyo** [comment]
Hi, please see attached screen shot. it works well in the command line but doesn't work in GUI

**Comment by mp035** [comment]
I hope this isn't too simplistic, but your screenshot doesn't seem to show the logger running.  Have you clicked the "Run" button?

**Comment by kangpyo** [comment]
yes, I clicked the "run" in both windows, but it doesn't response 
![Screenshot from 2022-12-06 18-45-18](https://user-images.githubusercontent.com/53060924/206618972-a657161d-14e3-4f9c-9786-00f415806c77.png)

**Comment by mp035** [comment]
Hi Again, thanks for the screenshot.  Sorry for all of the back and forth, and I'm sorry the application isn't working as it should.

Just some context, I am currently unable to get to my workshop to run any tests because I am stuck at home with a crushed foot after a motorcycle accident so I am trying to diagnose this issue without actually being able to test the system myself.

The latest screenshot you posted seems like the stylesheet has not loaded, what changed between the latest screenshot and the previous ones?

EDIT: Update, I have called in a favor and got my 365B at home.  I'll post back after testing.

**Comment by mp035** [comment]
Ok, again sorry for the back and forth, I have managed to get some test hardware and fixed the issue, please pull the latest commit and try again.  Let me know how you go.

**Comment by kangpyo** [comment]
Hi, sorry to hear that you had an accident. wish you recover soon. and also sorry that i posted the problem to simple. i was running around to deal with another problem at that moment. 
i just reinstalled the latest version and it work fantastically works!
i spent much time to figure out this issue different way but your update works best. thank you so much!. 
just one more question, is there a way to save the data?
i can use "select all" and copy and past in libreoffice but not sure you already built the function to save. 
thanks

**Comment by mp035** [comment]
You are most welcome.

![image](https://user-images.githubusercontent.com/9688384/206829218-6d61303d-f8e6-4599-9ad5-9bfd52764e2f.png)

Will save as csv.
